import { t } from '../../i18n';

/** Built-in CodeMirror controls and screen-reader announcements. Keep its $ tokens intact. */
export const codeMirrorPhrases = (): Record<string, string> => ({
    "Search": t("Search"),
    "Replace": t("Replace"),
    "next": t("next"),
    "previous": t("previous"),
    "all": t("all"),
    "match case": t("match case"),
    "regexp": t("regexp"),
    "by word": t("by word"),
    "replace": t("replace"),
    "replace all": t("replace all"),
    "close": t("close"),
    "Go to line": t("Go to line"),
    "go": t("go"),
    "current match": t("current match"),
    "on line": t("on line"),
    "replaced match on line $": t("replaced match on line $"),
    "replaced $ matches": t("replaced $ matches"),
    "Folded lines": t("Folded lines"),
    "Unfolded lines": t("Unfolded lines"),
    "to": t("to"),
    "folded code": t("folded code"),
    "unfold": t("unfold"),
    "Fold line": t("Fold line"),
    "Unfold line": t("Unfold line"),
    "Selection deleted": t("Selection deleted"),
    "Completions": t("Completions"),
    "Diagnostics": t("Diagnostics"),
    "No diagnostics": t("No diagnostics"),
    "Control character": t("Control character"),
});
